### ISSUE TITLE
Add tests for valid and invalid email addresses

### ISSUE THREAD

**Issue by damianb** [uncomnllc/gfm-mailer-prototype#11]
These tests should validate that an invalid string (something that isn't an email address, such as "abc") being specified for `to`, `cc`, `bcc`, `sender`, and `replyTo` all result in a request's rejection.

**Comment by edking21** [comment]
After reviewing #13, the tests should confirm the name string (all characters before the @) in an email to only allow [A-Za-z0-9-].

**Comment by edking21** [comment]
The name string will also allow base58 strings.

**Comment by damianb** [comment]
That is not correct.  We are only validating the requestID passed from the calling service.  `isemail` module will validate the supplied emails.

**Comment by damianb** [comment]
For reference, email validation implementation is within DispatchAPI [here](https://github.com/uncomnllc/gfm-mailer-prototype/blob/master/src/interfaces/DispatchApi.ts#L7).  Note `String.withConstraint`, which expects a boolean response for validation.  `isemail.validate` will return a boolean depending on if it considers the provided email valid or not.

**Comment by damianb** [comment]
Completed by #28
