### ISSUE TITLE
Add tests to validate dryRun functionality

### ISSUE THREAD

**Issue by damianb** [uncomnllc/gfm-mailer-prototype#15]
We need two tests, a positive and a negative test, to validate dryRun functionality.

One test needs to have a proper email attempt go through, then validate that the response correctly indicates that a dryRun occurred, and that no email was sent to the transport (perhaps checking `iwm.sentMailsCount`).

Other test needs to have a failing email attempt go through (we should use an empty json request body to keep it terse) and we need to validate that it still returns an error as expected.

**Comment by edking21** [comment]
Can I work on these two tests with my current branch or should I somehow sync with your latest changes?

Ed King / Software Engineer
UNCOMN, LLC
https://www.uncomn.com/<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.uncomn.com%2F&data=02%7C01%7Ceking%40uncomn.com%7Ce340b4ceb8114d7e158508d827dfb448%7C53a1c5bf868149f5aa47f4ed78e7a2bc%7C0%7C0%7C637303189088503298&sdata=d6wy%2BNu6UnmmL%2FLsPdwwWeWlQCLv%2FneXfrZIbdKrkR0%3D&reserved=0>
Cell: 314-920-3212
------------------------------
[cid:image001.png@01D67162.FD581430]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FuncomnLLC%2F&data=02%7C01%7Ceking%40uncomn.com%7Ce340b4ceb8114d7e158508d827dfb448%7C53a1c5bf868149f5aa47f4ed78e7a2bc%7C0%7C0%7C637303189088503298&sdata=RkC3sbSIJEXZ7v7D%2BgKkCz0%2BMJjuFBVfYJolOdpo19M%3D&reserved=0>  [cid:image002.png@01D67162.FD581430] <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FUNCOMN_LLC&data=02%7C01%7Ceking%40uncomn.com%7Ce340b4ceb8114d7e158508d827dfb448%7C53a1c5bf868149f5aa47f4ed78e7a2bc%7C0%7C0%7C637303189088513290&sdata=I5N4CIvoe0WZFG78JqtkcFjM%2Fjdjcdq1MNGNb3J2Nt8%3D&reserved=0>   [cid:image003.png@01D67162.FD581430] <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instagram.com%2Funcomn_llc%2F&data=02%7C01%7Ceking%40uncomn.com%7Ce340b4ceb8114d7e158508d827dfb448%7C53a1c5bf868149f5aa47f4ed78e7a2bc%7C0%7C0%7C637303189088513290&sdata=hI1ULFdKIjnTHNnOxf6la6VHRvc4JIDp%2BQ%2BwZS52trc%3D&reserved=0>   [cid:image004.png@01D67162.FD581430] <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCZu1q9JQkjD2mftp7HWLL0A%2F&data=02%7C01%7Ceking%40uncomn.com%7Ce340b4ceb8114d7e158508d827dfb448%7C53a1c5bf868149f5aa47f4ed78e7a2bc%7C0%7C0%7C637303189088513290&sdata=Fb5Ka1tE6CRQ1ATyw9yljzFyu5Z3H0TKtsRMF8ubJ8E%3D&reserved=0>

**Comment by damianb** [comment]
If you're concerned about my changes potentially affecting yours (which, the requestID bit would, probably), I would recommend reviewing my changes and then merging if they pass review.  From there, you can merge `origin/master` in to your branch after and continue.

I would recommend using individual branches for each issue you tackle.  Keeping them named somewhat relevant to the issue is good practice (brevity is good).

**Comment by damianb** [comment]
Closed by #20 merge.
